# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BonificacionCuota', models.FloatField()),
                ('fechaBonificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('fechaInactividad', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Igss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('cuota_igss', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaGenerar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_planilla', models.CharField(max_length=100)),
                ('apellido_planilla', models.CharField(max_length=100)),
                ('fecha_inicio_planilla', models.CharField(max_length=100)),
                ('igss_anio_planilla', models.CharField(max_length=100)),
                ('igss_cuota', models.CharField(max_length=100)),
                ('mes_planilla', models.CharField(max_length=100)),
                ('cuota_salario_planilla', models.CharField(max_length=100)),
                ('bonificacion_planilla', models.CharField(max_length=100, null=True)),
                ('retencion_planilla', models.CharField(max_length=100, null=True)),
                ('sueldoTotal_planilla', models.CharField(max_length=100)),
                ('sueldoLiquido_planilla', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RetencionCuota', models.FloatField()),
                ('fechaRetencion', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioOrdinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('cuota_salario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bonificacion',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Empleado'),
        ),
    ]
