# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('M', 'Activo'), ('F', 'Inactivo')], max_length=100),
        ),
    ]
