# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20161110_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaInactividad',
            field=models.DateField(blank=True),
        ),
    ]
